// <auto-generated />
using System;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250721162628_SeedVillaTable")]
    partial class SeedVillaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("VillaTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Pool, WiFi, Breakfast",
                            CreatedDate = new DateTime(2025, 7, 21, 21, 56, 28, 200, DateTimeKind.Local).AddTicks(1567),
                            Details = "This is a detailed description of the Royal Villa.",
                            ImageUrl = "https://example.com/royal-villa.jpg",
                            Name = "Royal Villa",
                            Occupancy = 4,
                            Rate = 200.0,
                            Sqft = 500,
                            UpdatedDate = new DateTime(2025, 7, 21, 21, 56, 28, 200, DateTimeKind.Local).AddTicks(1579)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Spa, Gym, WiFi",
                            CreatedDate = new DateTime(2025, 7, 21, 21, 56, 28, 200, DateTimeKind.Local).AddTicks(1582),
                            Details = "This is a detailed description of the Luxury Villa.",
                            ImageUrl = "https://example.com/luxury-villa.jpg",
                            Name = "Luxury Villa",
                            Occupancy = 6,
                            Rate = 300.0,
                            Sqft = 600,
                            UpdatedDate = new DateTime(2025, 7, 21, 21, 56, 28, 200, DateTimeKind.Local).AddTicks(1582)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
